# -*- coding: utf-8 -*-
"""volume_of_sphere.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/111_h8Q6kw3A3OaeuLAJ_1Io0mo9RoPzM
"""

import math
rad1 = 30
volume1 = (4/3) * math.pi * (rad1 ** 3)
print(f"Radius 30 = {volume1:.2f}")
rad2 = 40
volume2 = (4/3) * math.pi * (rad2 ** 3)
print(f"Radius 40 = {volume2:.2f}")